name: action-itemplate-ghpages
author: Itamar Carvalho
description: Action to publish auto-filled GitHub Pages from a custom set of templates or a pre-build theme.
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  templates_folder:
    description: "The relative path to the folder that contains your site's templates or the chosen theme id."
    required: true
    default: 'templates'
  allow_templates_subfolders:
    description: "Allow the templates to be stored in subfolders under templates_folder ('true'/'false')."
    required: false
    default: 'false'
  pages_branch:
    description: "Branch name for storing github pages"
    required: true
    default: 'gh-pages'
  pages_folder:
    description: "Name of the output folder where generated html will be stored."
    required: true
    default: 'docs'
  snippets_folder:
    description: "The relative path to the folder that contains your site's snippets, if any"
    required: false
    default: 'snippets'
  timezone: 
    description: "Time zone to calculate the update time"
    required: true
    # (default: America/Sao_Paulo, which is GMT-3 - sorry, I'm brazilian =) )
    default: 'America/Sao_Paulo'
  publish_readme_md:
    description: "Publish the README.md from the repository root in the generated page ('true'/'false')."
    required: false
    default: 'false'
  content_to_copy:
    description: "Folders or files to copy when publishing, keeping the relative path, separated by commas."
    required: false
    default: ''
  log_level:
    description: "The log level, according to the ones defined in java.util.logging.Level."
    required: false
    default: 'WARNING'
runs:
  using: 'docker'
  image: 'Dockerfile'
