name: action-itemplate-ghpages
author: Itamar Carvalho
description: Action to automatically publish GitHub Pages from a set of templates.
branding:
  icon: 'edit'
  color: 'blue'
inputs:
  templates_folder:
    description: "The relative path to the folder that contains your site's templates"
    required: true
    default: 'docs/templates'
  allow_templates_subfolders:
    description: "Allow the templates to be stored in subfolders under templates_folder ('true'/'false')."
    required: false
    default: 'false'
  pages_branch:
    description: "Branch name for storing github pages"
    required: true
    default: 'gh-pages'
  pages_folder:
    description: "Name of the output folder where generated html will be stored."
    required: true
    default: 'docs'
  snippets_folder:
    description: "The relative path to the folder that contains your site's snippets, if any"
    required: false
    default: 'docs/snippets'
  timezone: 
    description: "Time zone to calculate the update time"
    required: true
    # (default: America/Sao_Paulo, which is GMT-3 - sorry, I'm brazilian =) )
    default: 'America/Sao_Paulo'
runs:
  using: 'docker'
  image: 'Dockerfile'
